# Generated by Django 4.2.11 on 2024-04-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/profile-pic/'),
        ),
    ]
