# Generated by Django 4.2.11 on 2024-04-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_alter_profilemodel_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/profile-pic/default_profile_pic.png', null=True, upload_to='images/profile-pic/'),
        ),
    ]
