# Generated by Django 4.2.11 on 2024-04-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_alter_profilemodel_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='login42',
            field=models.CharField(default=None, max_length=7),
            preserve_default=False,
        ),
    ]
