# Generated by Django 4.2.11 on 2024-04-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_profilemodel_login42'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='login42',
            field=models.CharField(max_length=8),
        ),
    ]
