# Generated by Django 4.2.11 on 2024-04-04 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameCustomization',
            fields=[
                ('pseudonyme', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('board', models.CharField(max_length=50)),
                ('paddles', models.CharField(max_length=50)),
                ('ball', models.CharField(max_length=50)),
                ('score', models.CharField(max_length=50)),
                ('obstacle', models.CharField(max_length=50)),
                ('number_balls', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalDashboard',
            fields=[
                ('pseudonyme', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('total_party', models.IntegerField(default=0)),
                ('total_win', models.IntegerField(default=0)),
                ('total_loose', models.IntegerField(default=0)),
                ('dif_win_loose', models.IntegerField(default=0)),
                ('balls_hit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('pseudonyme', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('connected', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GamesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('opponent', models.CharField(max_length=10)),
                ('user_score', models.IntegerField(default=0)),
                ('opponent_score', models.IntegerField(default=0)),
                ('tournament_final', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_game.user')),
            ],
        ),
        migrations.CreateModel(
            name='GamesDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('opponent', models.CharField(max_length=10)),
                ('user_score', models.IntegerField(default=0)),
                ('opponent_score', models.IntegerField(default=0)),
                ('in_tournament', models.BooleanField(default=False)),
                ('tournament_final', models.BooleanField(default=False)),
                ('balls_hit', models.IntegerField(default=0)),
                ('boosts_catch', models.IntegerField(default=0)),
                ('max_speed', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_game.user')),
            ],
        ),
    ]
